name: etiya
description: "etiya_flutter_assignment"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  book_card:
    path: packages/book/book_card
  book_detail:
    path: packages/book/book_detail
  grpc:
  flutter_bloc:
  get_it:
  get:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  protobuf:
  flutter_lints: ^2.0.0
  test:


flutter:
  uses-material-design: true
